# Render blueprint for Project Nexus (Python web service + managed Postgres)
# Replace placeholders before committing. After pushing, create a Blueprint on Render
# that points to this repository and branch (main). Render will create services from
# this spec or you can import it when creating a new service.

services:
  - type: web
    name: nexus-web
    env: docker
    region: oregon
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        # generate locally (python -c "import secrets; print(secrets.token_urlsafe(50))")
        value: "<GENERATE_AND_PASTE_SECRET>"
      - key: DATABASE_URL
        # will be injected from the managed database defined below by name
        fromDatabase: nexus-db
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "<your-app>.onrender.com"
      - key: USE_S3
        value: "false"

# Managed Postgres database for the app. Render will provision this DB for you.
databases:
  - name: nexus-db
    engine: postgres
    version: "15"
    plan: starter
    region: oregon
    diskGB: 10
