# Generated by Django 4.2.25 on 2025-10-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_trigram_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_name_f603c0_idx',
            old_name='catalog_pro_name_idx',
        ),
    ]
\n
