# Generated by Django 4.2.25 on 2025-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_catalog_pro_name_idx_catalog_pro_name_f603c0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_backorder',
            field=models.BooleanField(default=False),
        ),
    ]
\n