# Generated by Django 4.2.25 on 2025-10-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_allow_backorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override price for this variant', max_digits=10, null=True)),
                ('inventory', models.IntegerField(default=0)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_slug_2b1eb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_price_2d2a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_created_eee82f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_categor_7c1c1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_categor_5a4a66_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_name_f603c0_idx',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_187601_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='catalog_pro_product_460665_idx'),
        ),
    ]
\n
