# Generated by Django 4.2.25 on 2025-10-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_allow_backorder'),
        ('orders', '0002_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('owner_type', models.CharField(help_text='e.g., cart, order, session', max_length=32)),
                ('owner_id', models.CharField(help_text='id of the owning entity', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('committed', 'Committed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='orders_stoc_product_631e68_idx'), models.Index(fields=['owner_type', 'owner_id'], name='orders_stoc_owner_t_022caa_idx')],
            },
        ),
    ]
\n
