# Generated by Django 4.2.25 on 2025-10-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productimage_productvariant_alter_product_options_and_more'),
        ('orders', '0005_cartitem_variant_orderitem_variant_sku_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
\n
