name: CI

on:
  push:
    branches: [ main, 'feat/jwt-auth' ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install project dependencies and test runner
          pip install -r requirements.txt pytest pytest-django

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do pg_isready -h 127.0.0.1 -p 5432 -U postgres -d test_db && break || sleep 1; done

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: "nexus.settings"
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: "nexus.settings"
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          python -m pytest -q

      - name: Run image upload integration test
        env:
          DJANGO_SETTINGS_MODULE: "nexus.settings"
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          python -m pytest -q tests/integration/test_product_image_upload.py

      - name: Collect static files (local)
        # Force local static collection in CI to validate static pipeline without requiring S3 creds
        env:
          USE_S3: '0'
          DJANGO_SETTINGS_MODULE: "nexus.settings"
        run: |
          python manage.py collectstatic --noinput

      - name: Build Docker image (validate Dockerfile)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: 'nexus-web:ci'

  s3-smoke:
    name: S3 smoke tests (moto)
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-s3
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install minimal dependencies for moto
        run: |
          python -m pip install --upgrade pip
          # include pytest and pytest-django so the job can run the test runner
          pip install moto boto3 django-storages pytest pytest-django

      - name: Run moto-backed S3 test
        env:
          DJANGO_SETTINGS_MODULE: "nexus.settings"
          USE_S3: '1'
          AWS_STORAGE_BUCKET_NAME: 'test-bucket'
          AWS_S3_BUCKET_NAME: 'test-bucket'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_REGION_NAME: 'us-east-1'
          AWS_S3_CUSTOM_DOMAIN: 'test-bucket.s3.amazonaws.com'
        run: |
          python -m pytest -q tests/integration/test_s3_upload.py
