name: Preflight

on:
  push:
    branches: [ main, feat/jwt-auth ]
  pull_request:
    branches: [ main, feat/jwt-auth ]

jobs:
  preflight-check:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: nexus.settings
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Syntax check (py_compile)
        run: |
          python -m py_compile $(git ls-files "**/*.py")

      - name: Test discovery (collect-only)
        run: |
          # Ensure Django settings module is available for DRF test imports
          python -m unittest discover --pattern "test*.py" --top-level-directory . --quiet
