name: Preflight checks

on:
  push:
    branches: [ '**' ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-workflows:
    name: Validate workflow YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate YAML files
        run: |
          python - <<'PY'
          import glob, sys, yaml
          errors = 0
          for p in glob.glob('.github/workflows/*.yml'):
              try:
                  with open(p, 'r', encoding='utf-8') as f:
                      list(yaml.safe_load_all(f))
              except Exception as e:
                  print(p + ':', e)
                  errors += 1
          if errors:
              sys.exit(1)
          print('All workflow YAML files parse OK')
          PY

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files
